### ISSUE TITLE
some items "impossible" to translate

### ISSUE THREAD

**Issue by athosbr99** [rtorr/vim-cheat-sheet#33]
![captura de tela 21](https://cloud.githubusercontent.com/assets/6440060/3806579/b7f9a2b4-1c4f-11e4-981f-8d0a7e7f548b.png)
some items that cannot be edited on the html file on lang are shown in english on the site.

I don't know what could be done, but I felt that should be reported.

**Comment by Melkor333** [comment]
If this would be implemented, some commands could also be adjusted a bit.
For example the commands `c`  `d` and `y` could be improved to tell that any movement Command can be added (since it is possible to use for example `c2w` to change the following 2 words). We could make

`cmovement :  change until movement`

and then add a tip saying something like:

> all movements described in the cursor movement sections can be used, except commands using ctrl. 
> For example c2w would change the next two words.

I'm not familiar with ruby, but I'd suggest that we add another list with variables in the _config.yml called 'variables' so we can call them in the page.html like this:

```
<!-- before -->
<li><kbd>:help keyword</kbd> - {{ page.global.commands.helpForKeyword }}</li>
<!-- after -->
<li><kbd>:help {{ page.variables.keyword}}</kbd> - {{ page.global.commands.helpForKeyword }}</li>

```

What do you think of this?
